name: superbuycuba
description: Aplicación móvil oficial para Super Buy Cuba
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  http: ^0.13.6
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.7
  fluttertoast: ^8.2.4
  intl: ^0.18.1
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png